### ISSUE TITLE
[BUG] Make Image in Movie's Card Responsive

### ISSUE THREAD

**Issue by ikrydev** [ikrydev/simple-movie-list#1]

**Comment by SiriusScaper** [comment]
What is the bug? I assume it's the content not being centered at breakpoints beyond ~390 to 750?

**Comment by ikrydev** [comment]
@SiriusScaper  make image in movie card responsive...

<img width="438" alt="Screen Shot 2019-10-22 at 12 10 33" src="https://user-images.githubusercontent.com/40247655/67260339-fa342700-f4c4-11e9-9606-bfed830e969e.png">

**Comment by vivekshah1801** [comment]
@ikrydev Hello, Can i work on this bug?

**Comment by ikrydev** [comment]
sure @vivekshah1801

**Comment by ikrydev** [comment]
Dont forget to follow me and give star to this repo ^_^ @vivekshah1801

**Comment by vivekshah1801** [comment]
@ikrydev Can you please help me how to set this repo on my local machine. I am not able to run this project on my local machine. I have node installed.

**Comment by ikrydev** [comment]
- Fork this repo, read [how to fork repo](https://help.github.com/articles/fork-a-repo/)
- Create branch with your topis issue, ex: `FixImage`. **Never use the `master` branch to create PR**.
  read [how creating branch](https://help.github.com/articles/creating-and-deleting-branches-within-your-repository/)
- clone your repo into your local machine
- `cd simple-movie-list`
- `npm install`
-  after you have done with issue
- commit your change and push to your branch
- Create Pull-Request to `master` branch in this repository, read [how creating PR](https://help.github.com/articles/creating-a-pull-request/)
- Don't forget to give 🌟 in this repository, you can check in [stargazers page](https://github.com/ikrydev/simple-movie-list/stargazers)
- You should follow github [@ikrydev](https://github.com/ikrydev)
- I will check your PRs and will **add `invalid` label** and **close the PRs** that not follow the steps
- Keep in mind, quality is always number one when creating PRs.

**Comment by ikrydev** [comment]
how @vivekshah1801  ?
