### ISSUE TITLE
Add How To Contribute Section to README.md

### ISSUE THREAD

**Issue by ikrydev** [ikrydev/simple-movie-list#3]
inside how to contribute

make sure to give start 🌟 in this repository, you can check in [stargazers page](https://github.com/ikrydev/simple-movie-list/stargazers) and follow github [@ikrydev](https://github.com/ikrydev)

**Comment by roccojiang** [comment]
@ikrydev I'd be willing to help out with this! Just to clarify – do you just want a message in `CONTRIBUTING.md` like this?

> make sure to give start 🌟 in this repository, you can check in stargazers pageand follow github @ikrydev

**Comment by ikrydev** [comment]
@rj14ng 
The contents are how to contribute to the project reactjs in this repository, it is in the form of steps starting from this fork repo to making a pull request.

and at the end of the step don't forget to follow github [@ikrydev](https://github.com/ikrydev) account and give a star to this repo

**Comment by roccojiang** [comment]
@ikrydev Alright – I'll work on it!

**Comment by ikrydev** [comment]
okay ...
dont forget to star this repo and follow my github ^_ @rj14ng

**Comment by roccojiang** [comment]
@ikrydev PR made! Please have a look and see if it's suitable

**Comment by ikrydev** [comment]
okay thanks
